### ISSUE TITLE
fails to build with freetype2 >= 2.5.1

### ISSUE THREAD

**Issue by jnumm** [djcsdy/swfmill#32]
This problem was reported to Debian as “swfmill: FTBFS: swft/swft_import_ttf.cpp:17:31: fatal error: freetype/tttables.h: No such file or directory”. It’s available at http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733356

Here’s the patch I submitted to the Debian maintainer. It is for 0.3.2 but the current master branch here has the same line.

``` patch
Description: Fix build failure with freetype 2.5.1
Author: Juhani Numminen <juhaninumminen0@gmail.com>
Bug-Debian: http://bugs.debian.org/733356

--- a/src/swft/swft_import_ttf.cpp
+++ b/src/swft/swft_import_ttf.cpp
@@ -14,7 +14,7 @@
 #include FT_OUTLINE_H
 #include "SWFShapeMaker.h"

-#include <freetype/tttables.h>
+#include FT_TRUETYPE_TABLES_H

 using namespace SWF;

```

**Comment by koji3** [comment]
I also had this bug and this change worked for me.
-#include <freetype/tttables.h>
+#include FT_TRUETYPE_TABLES_H

**Comment by djcsdy** [comment]
Fixed as of 36f5f8d60ce6474b6f712a7e54431860789aa077. The fix will be included in swfmill 0.3.5.
